apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../crds/base
- ../../base
- ../../operator/config
- ../../operator/overlays/dev-template
# - ../../console/overlays/dev-template
- quota.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: jvm-build-service-reqprocessor-image
  target:
    kind: Task
    name: maven
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: jvm-build-service-reqprocessor-image
  target:
    kind: Task
    name: gradle
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: S3_SYNC_ENABLED
          value: "true"
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- path: config.yaml
- path: system-config.yaml
