---
apiVersion: jvmbuildservice.io/v1alpha1
kind: JBSConfig
metadata:
  name: jvm-build-config
spec:
  enableRebuilds: true
  mavenBaseLocations:
    maven-repository-300-jboss: "https://repository.jboss.org/nexus/content/groups/public/"
    maven-repository-301-confluent: "https://packages.confluent.io/maven"
    maven-repository-302-redhat: "https://maven.repository.redhat.com/ga"
    maven-repository-303-jitpack: "https://jitpack.io"
    maven-repository-304-gradle: "https://repo.gradle.org/artifactory/libs-releases"
