name: Java CI

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        working-directory: java-components
        run: mvn -V -B package -Dvalidate-format
      - name: Codecov
        uses: codecov/codecov-action@v3
